[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "PaddleCppApiDocs"
authors = [{name = "Liyulingyue", email = "None"}]
dynamic = ["version", "description"]
